<?php
/**
 * Main plugin bootstrap.
 *
 * @package EasyTestimonialBlocks
 */

// Stop direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Boots the plugin: wires up block registration, the admin page, and the
 * post-activation redirect.
 */
final class ETB_Plugin {

	/**
	 * Singleton instance.
	 *
	 * @var self|null
	 */
	private static $instance = null;

	/**
	 * Boots the plugin.
	 *
	 * @return self
	 */
	public static function init() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Constructor.
	 */
	private function __construct() {
		new ETB_Blocks();

		if ( is_admin() ) {
			new ETB_Admin();
		}

		add_action( 'activated_plugin', array( $this, 'redirect_to_admin_page' ) );
	}

	/**
	 * Redirects to the plugin's admin page right after it is activated.
	 *
	 * @param string $plugin Basename of the plugin that was just activated.
	 */
	public function redirect_to_admin_page( $plugin ) {
		if ( ETB_BASENAME !== $plugin ) {
			return;
		}

		// Skip the redirect during bulk activation from the plugins list.
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only isset check of a flag generated by WordPress core on the activation request; no nonce is available here.
		if ( isset( $_GET['activate-multi'] ) ) {
			return;
		}

		wp_safe_redirect( admin_url( 'tools.php?page=etb-blocks' ) );
		exit;
	}
}
